import { initializeApp } from "firebase/app";
import { getFirestore, collection, doc, writeBatch } from "firebase/firestore";


const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY,
  authDomain: process.env.FIREBASE_AUTH_DOMAIN,
  databaseURL: process.env.FIREBASE_DATABASE_URL,
  projectId: process.env.FIREBASE_PROJECT_ID,
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.FIREBASE_APP_ID,
  measurementId: process.env.FIREBASE_MEASUREMENT_ID,
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);



// Your product data
const productList = [
  {
    "slug": "amethi-moonj-products",
    "name": "Moonj Products",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Amethi",
    "craft": "Moonj Products",
    "artisan": "",
    "image": "https://example.com/images/amethi-moonj-products.jpg",
    "description": "Authentic Moonj Products from Amethi, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "amroha-dholak-and-other-instruments",
    "name": "Dholak & Other instruments",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Amroha",
    "craft": "Dholak & Other instruments",
    "artisan": "",
    "image": "https://example.com/images/amroha-dholak-and-other-instruments.jpg",
    "description": "Authentic Dholak & Other instruments from Amroha, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "ayodhya-jaggery-products",
    "name": "Jaggery Products",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Ayodhya",
    "craft": "Jaggery Products",
    "artisan": "",
    "image": "https://example.com/images/ayodhya-jaggery-products.jpg",
    "description": "Authentic Jaggery Products from Ayodhya, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "azamgarh-black-pottery-artefacts---reshmi-saan",
    "name": "Black Pottery Artefacts / Reshmi Saan",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Azamgarh",
    "craft": "Black Pottery Artefacts / Reshmi Saan",
    "artisan": "",
    "image": "https://example.com/images/azamgarh-black-pottery-artefacts---reshmi-saan.jpg",
    "description": "Authentic Black Pottery Artefacts / Reshmi Saan from Azamgarh, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "baghpat-home-decorative-goods",
    "name": "Home Decorative Goods",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Baghpat",
    "craft": "Home Decorative Goods",
    "artisan": "",
    "image": "https://example.com/images/baghpat-home-decorative-goods.jpg",
    "description": "Authentic Home Decorative Goods from Baghpat, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "bahraich-wheat-stalk",
    "name": "Wheat Stalk",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Bahraich",
    "craft": "Wheat Stalk",
    "artisan": "",
    "image": "https://example.com/images/bahraich-wheat-stalk.jpg",
    "description": "Authentic Wheat Stalk from Bahraich, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "balia-bindi-(tikuli)",
    "name": "Bindi (Tikuli)",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Balia",
    "craft": "Bindi (Tikuli)",
    "artisan": "",
    "image": "https://example.com/images/balia-bindi-(tikuli).jpg",
    "description": "Authentic Bindi (Tikuli) from Balia, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "banda-shazay-stone-craft",
    "name": "Shazay Stone Craft",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Banda",
    "craft": "Shazay Stone Craft",
    "artisan": "",
    "image": "https://example.com/images/banda-shazay-stone-craft.jpg",
    "description": "Authentic Shazay Stone Craft from Banda, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "barabanki-mint---textile-products",
    "name": "Mint / Textile products",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Barabanki",
    "craft": "Mint / Textile products",
    "artisan": "",
    "image": "https://example.com/images/barabanki-mint---textile-products.jpg",
    "description": "Authentic Mint / Textile products from Barabanki, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "bareilly-zari-and-zardozi-(jhumka)",
    "name": "Zari & Zardozi (Jhumka)",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Bareilly",
    "craft": "Zari & Zardozi (Jhumka)",
    "artisan": "",
    "image": "https://example.com/images/bareilly-zari-and-zardozi-(jhumka).jpg",
    "description": "Authentic Zari & Zardozi (Jhumka) from Bareilly, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "basti/bijnor-wood-craft",
    "name": "Wood Craft",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Basti/Bijnor",
    "craft": "Wood Craft",
    "artisan": "",
    "image": "https://example.com/images/basti/bijnor-wood-craft.jpg",
    "description": "Authentic Wood Craft from Basti/Bijnor, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "bhadohi-carpet-(dauri)",
    "name": "Carpet (Dauri)",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Bhadohi",
    "craft": "Carpet (Dauri)",
    "artisan": "",
    "image": "https://example.com/images/bhadohi-carpet-(dauri).jpg",
    "description": "Authentic Carpet (Dauri) from Bhadohi, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "bulandshahar/khurja-ceramic-products",
    "name": "Ceramic Products",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Bulandshahar/Khurja",
    "craft": "Ceramic Products",
    "artisan": "",
    "image": "https://example.com/images/bulandshahar/khurja-ceramic-products.jpg",
    "description": "Authentic Ceramic Products from Bulandshahar/Khurja, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "chitrakoot-wood-arts-toys",
    "name": "Wood Arts/Toys",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Chitrakoot",
    "craft": "Wood Arts/Toys",
    "artisan": "",
    "image": "https://example.com/images/chitrakoot-wood-arts-toys.jpg",
    "description": "Authentic Wood Arts/Toys from Chitrakoot, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "deoria-decorative-products",
    "name": "Decorative Products",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Deoria",
    "craft": "Decorative Products",
    "artisan": "",
    "image": "https://example.com/images/deoria-decorative-products.jpg",
    "description": "Authentic Decorative Products from Deoria, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "etah-ghungroo-bells-and-brass-products",
    "name": "Ghungroo/Bells & Brass Products",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Etah",
    "craft": "Ghungroo/Bells & Brass Products",
    "artisan": "",
    "image": "https://example.com/images/etah-ghungroo-bells-and-brass-products.jpg",
    "description": "Authentic Ghungroo/Bells & Brass Products from Etah, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "fatehpur-bedsheets",
    "name": "Bedsheets",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Fatehpur",
    "craft": "Bedsheets",
    "artisan": "",
    "image": "https://example.com/images/fatehpur-bedsheets.jpg",
    "description": "Authentic Bedsheets from Fatehpur, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "firozabad-glassware-chudiyan",
    "name": "Glassware/Chudiyan",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Firozabad",
    "craft": "Glassware/Chudiyan",
    "artisan": "",
    "image": "https://example.com/images/firozabad-glassware-chudiyan.jpg",
    "description": "Authentic Glassware/Chudiyan from Firozabad, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "ghaziabad-jute-wall-hangings",
    "name": "Jute Wall Hangings",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Ghaziabad",
    "craft": "Jute Wall Hangings",
    "artisan": "",
    "image": "https://example.com/images/ghaziabad-jute-wall-hangings.jpg",
    "description": "Authentic Jute Wall Hangings from Ghaziabad, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "gorakhpur-terracotta",
    "name": "Terracotta",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Gorakhpur",
    "craft": "Terracotta",
    "artisan": "",
    "image": "https://example.com/images/gorakhpur-terracotta.jpg",
    "description": "Authentic Terracotta from Gorakhpur, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "hardoi-handloom-products",
    "name": "Handloom Products",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Hardoi",
    "craft": "Handloom Products",
    "artisan": "",
    "image": "https://example.com/images/hardoi-handloom-products.jpg",
    "description": "Authentic Handloom Products from Hardoi, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "hathras-hing-processing",
    "name": "Hing Processing",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Hathras",
    "craft": "Hing Processing",
    "artisan": "",
    "image": "https://example.com/images/hathras-hing-processing.jpg",
    "description": "Authentic Hing Processing from Hathras, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "jaunpur-handmade-paper-arts",
    "name": "Handmade Paper Arts",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Jaunpur",
    "craft": "Handmade Paper Arts",
    "artisan": "",
    "image": "https://example.com/images/jaunpur-handmade-paper-arts.jpg",
    "description": "Authentic Handmade Paper Arts from Jaunpur, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "jaupur-woollen-carpets",
    "name": "Woollen Carpets",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Jaupur",
    "craft": "Woollen Carpets",
    "artisan": "",
    "image": "https://example.com/images/jaupur-woollen-carpets.jpg",
    "description": "Authentic Woollen Carpets from Jaupur, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "jhansi-soft-toys",
    "name": "Soft Toys",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Jhansi",
    "craft": "Soft Toys",
    "artisan": "",
    "image": "https://example.com/images/jhansi-soft-toys.jpg",
    "description": "Authentic Soft Toys from Jhansi, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "kannauj-attar,-perfume",
    "name": "Attar, Perfume",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Kannauj",
    "craft": "Attar, Perfume",
    "artisan": "",
    "image": "https://example.com/images/kannauj-attar,-perfume.jpg",
    "description": "Authentic Attar, Perfume from Kannauj, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "kanpur-dehat-zinc-utensils",
    "name": "Zinc Utensils",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Kanpur Dehat",
    "craft": "Zinc Utensils",
    "artisan": "",
    "image": "https://example.com/images/kanpur-dehat-zinc-utensils.jpg",
    "description": "Authentic Zinc Utensils from Kanpur Dehat, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "kanpur-nagar-leather-goods",
    "name": "Leather Goods",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Kanpur Nagar",
    "craft": "Leather Goods",
    "artisan": "",
    "image": "https://example.com/images/kanpur-nagar-leather-goods.jpg",
    "description": "Authentic Leather Goods from Kanpur Nagar, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "kasganj-zari-zardozi",
    "name": "Zari Zardozi",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Kasganj",
    "craft": "Zari Zardozi",
    "artisan": "",
    "image": "https://example.com/images/kasganj-zari-zardozi.jpg",
    "description": "Authentic Zari Zardozi from Kasganj, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "kaushambi-banana-and-guava",
    "name": "Banana & Guava",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Kaushambi",
    "craft": "Banana & Guava",
    "artisan": "",
    "image": "https://example.com/images/kaushambi-banana-and-guava.jpg",
    "description": "Authentic Banana & Guava from Kaushambi, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "lakhimpur-kheri-tribal-craft",
    "name": "Tribal Craft",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Lakhimpur Kheri",
    "craft": "Tribal Craft",
    "artisan": "",
    "image": "https://example.com/images/lakhimpur-kheri-tribal-craft.jpg",
    "description": "Authentic Tribal Craft from Lakhimpur Kheri, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "lalitpur-zari-silk-saree",
    "name": "Zari Silk Saree",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Lalitpur",
    "craft": "Zari Silk Saree",
    "artisan": "",
    "image": "https://example.com/images/lalitpur-zari-silk-saree.jpg",
    "description": "Authentic Zari Silk Saree from Lalitpur, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "lucknow-chikankari-and-zari-zardozi",
    "name": "Chikankari & Zari Zardozi",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Lucknow",
    "craft": "Chikankari & Zari Zardozi",
    "artisan": "",
    "image": "https://example.com/images/lucknow-chikankari-and-zari-zardozi.jpg",
    "description": "Authentic Chikankari & Zari Zardozi from Lucknow, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "mahasajganj-furniture",
    "name": "Furniture",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Mahasajganj",
    "craft": "Furniture",
    "artisan": "",
    "image": "https://example.com/images/mahasajganj-furniture.jpg",
    "description": "Authentic Furniture from Mahasajganj, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "mahoba-gaurra-stone-craft",
    "name": "Gaurra Stone Craft",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Mahoba",
    "craft": "Gaurra Stone Craft",
    "artisan": "",
    "image": "https://example.com/images/mahoba-gaurra-stone-craft.jpg",
    "description": "Authentic Gaurra Stone Craft from Mahoba, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "mainpuri-tarkashi-art",
    "name": "Tarkashi Art",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Mainpuri",
    "craft": "Tarkashi Art",
    "artisan": "",
    "image": "https://example.com/images/mainpuri-tarkashi-art.jpg",
    "description": "Authentic Tarkashi Art from Mainpuri, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "mathura-thakurji-costume-kanthimala",
    "name": "Thakurji Costume/Kanthimala",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Mathura",
    "craft": "Thakurji Costume/Kanthimala",
    "artisan": "",
    "image": "https://example.com/images/mathura-thakurji-costume-kanthimala.jpg",
    "description": "Authentic Thakurji Costume/Kanthimala from Mathura, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "meerut-sports-goods",
    "name": "Sports Goods",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Meerut",
    "craft": "Sports Goods",
    "artisan": "",
    "image": "https://example.com/images/meerut-sports-goods.jpg",
    "description": "Authentic Sports Goods from Meerut, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "mirzapur-carpet-and-brass-industry",
    "name": "Carpet & Brass Industry",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Mirzapur",
    "craft": "Carpet & Brass Industry",
    "artisan": "",
    "image": "https://example.com/images/mirzapur-carpet-and-brass-industry.jpg",
    "description": "Authentic Carpet & Brass Industry from Mirzapur, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "muzaffarnagar-jaggery-products",
    "name": "Jaggery Products",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Muzaffarnagar",
    "craft": "Jaggery Products",
    "artisan": "",
    "image": "https://example.com/images/muzaffarnagar-jaggery-products.jpg",
    "description": "Authentic Jaggery Products from Muzaffarnagar, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "pilibhit-basori-and-wooden-products",
    "name": "Basori and Wooden Products",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Pilibhit",
    "craft": "Basori and Wooden Products",
    "artisan": "",
    "image": "https://example.com/images/pilibhit-basori-and-wooden-products.jpg",
    "description": "Authentic Basori and Wooden Products from Pilibhit, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "pratapgarh-amla-products",
    "name": "Amla Products",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Pratapgarh",
    "craft": "Amla Products",
    "artisan": "",
    "image": "https://example.com/images/pratapgarh-amla-products.jpg",
    "description": "Authentic Amla Products from Pratapgarh, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "prayagraj-moonj-products",
    "name": "Moonj Products",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Prayagraj",
    "craft": "Moonj Products",
    "artisan": "",
    "image": "https://example.com/images/prayagraj-moonj-products.jpg",
    "description": "Authentic Moonj Products from Prayagraj, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "rampur-knives",
    "name": "Knives",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Rampur",
    "craft": "Knives",
    "artisan": "",
    "image": "https://example.com/images/rampur-knives.jpg",
    "description": "Authentic Knives from Rampur, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "saharanpur-wood-carving",
    "name": "Wood Carving",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Saharanpur",
    "craft": "Wood Carving",
    "artisan": "",
    "image": "https://example.com/images/saharanpur-wood-carving.jpg",
    "description": "Authentic Wood Carving from Saharanpur, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "sambhal-horn-bone-products",
    "name": "Horn-Bone Products",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Sambhal",
    "craft": "Horn-Bone Products",
    "artisan": "",
    "image": "https://example.com/images/sambhal-horn-bone-products.jpg",
    "description": "Authentic Horn-Bone Products from Sambhal, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "sant-kabir-nagar-brass-utensils",
    "name": "Brass Utensils",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Sant Kabir Nagar",
    "craft": "Brass Utensils",
    "artisan": "",
    "image": "https://example.com/images/sant-kabir-nagar-brass-utensils.jpg",
    "description": "Authentic Brass Utensils from Sant Kabir Nagar, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "shrawasti-tribal-craft-and-furniture",
    "name": "Tribal Craft and Furniture",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Shrawasti",
    "craft": "Tribal Craft and Furniture",
    "artisan": "",
    "image": "https://example.com/images/shrawasti-tribal-craft-and-furniture.jpg",
    "description": "Authentic Tribal Craft and Furniture from Shrawasti, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "sitapur-khadi-and-carpets",
    "name": "Khadi and Carpets",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Sitapur",
    "craft": "Khadi and Carpets",
    "artisan": "",
    "image": "https://example.com/images/sitapur-khadi-and-carpets.jpg",
    "description": "Authentic Khadi and Carpets from Sitapur, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "sultanpur-moonj-products",
    "name": "Moonj Products",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Sultanpur",
    "craft": "Moonj Products",
    "artisan": "",
    "image": "https://example.com/images/sultanpur-moonj-products.jpg",
    "description": "Authentic Moonj Products from Sultanpur, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "varanasi-silk-products-and-gulabi-minakari-saree",
    "name": "Silk Products & Gulabi Minakari Saree",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Varanasi",
    "craft": "Silk Products & Gulabi Minakari Saree",
    "artisan": "",
    "image": "https://example.com/images/varanasi-silk-products-and-gulabi-minakari-saree.jpg",
    "description": "Authentic Silk Products & Gulabi Minakari Saree from Varanasi, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "lucknow-jute-work",
    "name": "Jute Work",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Lucknow",
    "craft": "Jute Work",
    "artisan": "",
    "image": "https://example.com/images/lucknow-jute-work.jpg",
    "description": "Authentic Jute Work from Lucknow, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  },
  {
    "slug": "lucknow-honey",
    "name": "Honey",
    "price": 1000,
    "originalPrice": 1200,
    "region": "Uttar Pradesh",
    "district": "Lucknow",
    "craft": "Honey",
    "artisan": "",
    "image": "https://example.com/images/lucknow-honey.jpg",
    "description": "Authentic Honey from Lucknow, Uttar Pradesh.",
    "giTag": false,
    "rating": 4.5,
    "reviews": 20
  }
];

// Asynchronous function to upload the products
async function uploadProducts() {
  // Create a new batch
  const batch = writeBatch(db);
  
  // Get a reference to the 'products' collection
  const productsCollectionRef = collection(db, "products");

  // Iterate over the product list and add each item to the batch
  productList.forEach(item => {
    // Create a new document reference with a unique, auto-generated ID
    const newDocRef = doc(productsCollectionRef); 
    
    // Add the set operation to the batch.
    batch.set(newDocRef, item);
  });

  try {
    // Commit the batch to save all documents at once
    await batch.commit();
    console.log("All products uploaded successfully with auto-generated IDs!");
  } catch (error) {
    console.error("Error writing batch:", error);
  }
}

// Call the function to start the upload process
uploadProducts()